[project]
name = "qdrant-manage"
version = "0.1.0"
description = "Qdrant management CLI tool"
requires-python = ">=3.12"
dependencies = [
    "qdrant-client>=1.9.0",
    "typer>=0.12.0",
    "rich>=13.0.0",
]

