[project]
name = "1-minio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "minio>=7.2.15",
    "python-magic>=0.4.27",
]
