[project]
name = "qdrant-document-search"
version = "0.1.0"
description = "Document chunking and semantic search with Qdrant"
requires-python = ">=3.12"
dependencies = [
    "qdrant-client>=1.9.0",
    "sentence-transformers>=4.1.0",
]

