[project]
name = "ollama-react-agent"
version = "0.1.0"
description = "A ReAct (Reason and Act) AI agent using Ollama"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.4.5",
    "yfinance>=0.2.54",
]